version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  Alexander Caesario Bangun
  Github Page for Operating Systems 2021-2 (odd semester)
  The template is taken from https://template.vlsm.org/template.zip
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "My Log"
  link:      "https://whenwe177.github.io/os212/TXT/mylog.txt"
- navbar:    "GitHub"
  link:      "https://github.com/whenwe177/os212/"
title:       "Alexander Caesario Bangun OS212"
lang:        "en-US"
author:      "Alexander Caesario Bangun"
address:     "Pontianak, Indonesia"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://whenwe177.github.io/os212/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/whenwe177/os212/"


